[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["cargo"] }
home = "0.5.4"
inquire = "0.5.3"
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.7.2"
url = "2"
